86b1u14wh
tracet2t/Digital-Logbook pull request #24
Opened 2024-08-29 12:39 UTC by AynulAmna

Changes has been done as per the review . Now, mentor able to register students and it will be stored in DB.

2024-08-30 07:03 UTC, bsaranga requested changes

2024-08-30 07:03 UTC, bsaranga commented on server/src/services/prisma.ts
> +import { PrismaClient } from '@prisma/client';
Let's use the Prisma singleton once Lakshanan commits it

2024-08-30 07:03 UTC, bsaranga commented on server/src/app/mentor-register/page.tsx
> +     redirect('/mentor-register/success');
Let's not redirect. Making this a client component and using a server action is much preferred

2024-08-30 15:05 UTC, AynulAmna commented on server/src/services/prisma.ts
> +import { PrismaClient } from '@prisma/client';
done . please check and review

2024-08-30 15:06 UTC, AynulAmna commented on server/src/app/mentor-register/page.tsx
> +     redirect('/mentor-register/success');
used user action please review

2024-08-31 17:59 UTC, AynulAmna commented
Conflicts resolved

2024-09-02 08:42 UTC, bsaranga approved these changes
The random password generated must be picked up by the emailing module and sent to student email. @AynulAmna connect with the person who made the emailing module.

2024-09-02 08:42 UTC, merged