temp: Removed cloned button import
tracet2t/Digital-Logbook pull request #32
Opened 2024-08-31 10:43 UTC by LakshananS

2024-08-31 11:58 UTC, bsaranga requested changes

2024-08-31 11:58 UTC, bsaranga commented on server/src/components/calendar.tsx
>  import { Input } from "antd";
Let's replace ant-design components with ShadCn.

2024-08-31 11:58 UTC, bsaranga commented
Please replace all antd usage with equivalent shadcn components. And remove the antd package.

2024-08-31 13:20 UTC, LakshananS commented
Okay. Noted I will change all the Ant design codes.

2024-09-01 05:00 UTC, LakshananS commented
Removed all antd package and components. Created new shadcn/ui components for input and text area. Implemented those code with frontend.

2024-09-01 05:22 UTC, bsaranga approved these changes

2024-09-01 05:22 UTC, bsaranga commented on package.json
> +{}
Let's remove this

2024-09-01 05:22 UTC, bsaranga commented on package-lock.json
> +{
Let's remove this

2024-09-01 05:22 UTC, merged

2024-09-01 05:42 UTC, LakshananS commented on package.json
> +{}
I removed those file