3f5a9a7kq
tracet2t/Digital-Logbook pull request #39
Opened 2024-09-05 15:23 UTC by thlurte

Following features have been integrated from different branches

- [x] Mentor's home page (UI/UX) `86b1u16yh` @NushaMBZ 
- [x] Reset Password Page (UI/UX) `86b1tvmtu` @s92068606
- [x] Login Page (UI/UX) `86b1tvmry` @s92068606 
- [x] Student's home Page (UI/UX)   `86b1tvpc8` @s92068606 
- [x] Registration Form and Email Design `86b1u1981` @NaRkIsJaHaN 
- [x] Retrieve and Display historical activity `86b1u14r5` `86b1u14r5` @NaRkIsJaHaN `Minhaj (minhajnazeer395@gmail.com)` 
- [x]  Mentor registering Student Form `86b1u14wh` @AynulAmna  
- [x]  Activity Logging Model `86b1tvpe1` @NaRkIsJaHaN  
- [x]  Add & Manage Activity `86b1tvpke` @LakshananS 
- [x]  JWT Authentication `86b1u0xkk` @Mohamedshazan 
- [x] Registration email with password reset link `86b1u14d8` @AM-ASKY-97

2024-09-05 15:25 UTC, NaRkIsJaHaN approved these changes

2024-09-05 15:26 UTC, s92068606 approved these changes

2024-09-05 15:26 UTC, NushaMBZ approved these changes

2024-09-05 15:57 UTC, AynulAmna approved these changes

2024-09-10 05:29 UTC, bsaranga requested changes
Attend to changes.

2024-09-10 05:29 UTC, bsaranga commented on server/prisma/seed.ts
>    await prisma.user.deleteMany({});
Remove the empty query object `{}` and call the `deleteMany` method without arguments.

2024-09-10 05:29 UTC, bsaranga commented on server/prisma/seed.ts
Remove the current `require` based imports and add the following:

```
import { PrismaClient } from "@prisma/client";
import * as bcrypt from 'bcrypt-ts'
```

Rename the file extension to `.mjs` and update the seed script in `package.json`

2024-09-10 07:01 UTC, thlurte commented on server/prisma/seed.ts
>    await prisma.user.deleteMany({});
the empty objects have been removed.

2024-09-10 07:02 UTC, thlurte commented on server/prisma/seed.ts
as requested, the changes have been made

2024-09-10 07:58 UTC, bsaranga approved these changes

2024-09-10 07:58 UTC, merged